export const RESTAURANT_REPORT_GROUPS = [
  { id: 'overview', title: 'Overview' },
  { id: 'sales', title: 'Sales' },
  { id: 'payments', title: 'Payments' },
  { id: 'operations', title: 'Operations' },
  { id: 'customers_profit', title: 'Customers and Profit' },
  { id: 'requires_data', title: 'Requires Additional Data' },
]

const commonFilters = ['datePreset', 'startDate', 'endDate']
const salesFilters = [...commonFilters, 'orderType', 'paymentStatus', 'orderStatus', 'source']
const paymentFilters = [...commonFilters, 'paymentMethod', 'paymentStatus', 'source', 'customerSearch']

export const RESTAURANT_REPORT_DEFINITIONS = [
  {
    id: 'executive-summary',
    group: 'overview',
    title: 'Executive Summary',
    description: 'High-level restaurant sales, collection, outstanding, and profit position with today\'s highlights, best-selling items, peak hours, and top payment methods.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: commonFilters,
    kpiKeys: ['grossSales', 'netSales', 'collectedAmount', 'outstandingAmount', 'netProfit'],
    breakdownKey: 'profitability',
    exportLabel: 'Executive Summary',
  },
  {
    id: 'daily-closing',
    group: 'overview',
    title: 'Daily Closing',
    description: 'Complete daily closing report with executive summary, payment breakdown, category sales, top 10 items, cash drawer reconciliation, shift summary, expenses, and customer statistics.',
    capability: 'ready',
    limitationMessage: 'Cash reconciliation values appear once shifts are settled.',
    supportedFilters: commonFilters,
    kpiKeys: ['openingCash', 'cashReceived', 'onlineReceived', 'approvedExpenses', 'cashReconciliationAvailable', 'cashDifference'],
    breakdownKey: 'cashReconciliation',
    exportLabel: 'Daily Closing',
  },
  {
    id: 'orders',
    group: 'sales',
    title: 'Orders',
    description: 'Billed, pending, due, partial, paid, and cancelled restaurant orders.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: salesFilters,
    kpiKeys: ['billedOrders', 'totalSales', 'averageOrderValue', 'cancellations'],
    breakdownKey: 'billedOrdersByStatus',
    exportLabel: 'Order Report',
  },
  {
    id: 'item-sales',
    group: 'sales',
    title: 'Item Sales',
    description: 'Menu item quantity, revenue, discount, and cost from billed non-cancelled orders.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: salesFilters,
    kpiKeys: ['itemSales', 'costOfGoodsSold', 'grossProfit'],
    breakdownKey: 'itemSales',
    exportLabel: 'Item Sales',
  },
  {
    id: 'category-sales',
    group: 'sales',
    title: 'Category Sales',
    description: 'Category-level sales where item category exists on source rows.',
    capability: 'partial',
    limitationMessage: 'Category reporting depends on category being stored on each restaurant item row.',
    supportedFilters: salesFilters,
    kpiKeys: ['categorySales', 'netSales', 'grossProfit'],
    breakdownKey: 'categorySales',
    exportLabel: 'Category Sales',
  },
  {
    id: 'order-type-performance',
    group: 'sales',
    title: 'Order Type Performance',
    description: 'Dine-in, takeaway, delivery, and invoice-order sales split.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: salesFilters,
    kpiKeys: ['netSales', 'totalSales', 'averageOrderValue'],
    breakdownKey: 'salesByOrderType',
    exportLabel: 'Order Type Performance',
  },
  {
    id: 'hourly-sales',
    group: 'sales',
    title: 'Hourly Sales',
    description: 'Order volume by created hour for normalized rows with valid dates.',
    capability: 'partial',
    limitationMessage: 'Rows with invalid or missing createdAt are not assigned to an hour.',
    supportedFilters: salesFilters,
    kpiKeys: ['ordersByHour', 'billedOrders', 'netSales'],
    breakdownKey: 'ordersByHour',
    exportLabel: 'Hourly Sales',
  },
  {
    id: 'payment-collection',
    group: 'payments',
    title: 'Payment Collection',
    description: 'Collected amount by payment method from billed non-cancelled orders.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: paymentFilters,
    kpiKeys: ['collectedAmount', 'cashReceived', 'onlineReceived'],
    breakdownKey: 'collectionsByPaymentMethod',
    exportLabel: 'Payment Collection',
  },
  {
    id: 'due-partial-payments',
    group: 'payments',
    title: 'Due and Partial Payments',
    description: 'Outstanding amount and partially collected order balances.',
    capability: 'partial',
    limitationMessage: 'Separate due recovery payment records are not stored; this report shows period order outstanding only.',
    supportedFilters: paymentFilters,
    kpiKeys: ['outstandingAmount', 'periodOrderOutstanding', 'storedCustomerCreditBalance'],
    breakdownKey: 'customerPerformance',
    exportLabel: 'Due and Partial Payments',
  },
  {
    id: 'tax-service-charges',
    group: 'payments',
    title: 'Tax and Service Charges',
    description: 'Billed tax and service charge totals from normalized order totals.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: salesFilters,
    kpiKeys: ['tax', 'serviceCharges', 'netSales'],
    breakdownKey: 'taxRows',
    exportLabel: 'Tax and Service Charges',
  },
  {
    id: 'discounts',
    group: 'payments',
    title: 'Discounts',
    description: 'Discount values from billed non-cancelled orders and item rows.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: salesFilters,
    kpiKeys: ['discounts', 'grossSales', 'netSales'],
    breakdownKey: 'discountRows',
    exportLabel: 'Discounts',
  },
  {
    id: 'table-performance',
    group: 'operations',
    title: 'Table Performance',
    description: 'Table sales, order count, and collection from billed dine-in rows.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: [...salesFilters, 'table'],
    kpiKeys: ['tablePerformance', 'netSales', 'collectedAmount'],
    breakdownKey: 'tablePerformance',
    exportLabel: 'Table Performance',
  },
  {
    id: 'kot-performance',
    group: 'operations',
    title: 'KOT Performance',
    description: 'KOT status counts and average preparation time from restaurant orders.',
    capability: 'partial',
    limitationMessage: 'Average preparation time depends on prepTime being stored on source rows.',
    supportedFilters: [...commonFilters, 'orderStatus', 'table'],
    kpiKeys: ['kotStatus'],
    breakdownKey: 'kotStatus',
    exportLabel: 'KOT Performance',
  },
  {
    id: 'cancellations',
    group: 'operations',
    title: 'Cancellations',
    description: 'Cancelled orders and cancellation reasons without financial contribution.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: [...commonFilters, 'orderType', 'source', 'table', 'customerSearch'],
    kpiKeys: ['cancellations'],
    breakdownKey: 'cancellations',
    exportLabel: 'Cancellations',
  },
  {
    id: 'customer-sales',
    group: 'customers_profit',
    title: 'Customer Sales',
    description: 'Customer sales, paid amount, period outstanding, and stored credit balance.',
    capability: 'partial',
    limitationMessage: 'Stored customer credit balance is separate from period order outstanding.',
    supportedFilters: [...paymentFilters, 'orderType'],
    kpiKeys: ['customerPerformance', 'periodOrderOutstanding', 'storedCustomerCreditBalance'],
    breakdownKey: 'customerPerformance',
    exportLabel: 'Customer Sales',
  },
  {
    id: 'cost-profit',
    group: 'customers_profit',
    title: 'Cost and Profit',
    description: 'COGS, gross profit, approved expenses, and net profit without clamping losses.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: salesFilters,
    kpiKeys: ['costOfGoodsSold', 'grossProfit', 'approvedExpenses', 'netProfit'],
    breakdownKey: 'profitability',
    exportLabel: 'Cost and Profit',
  },
  {
    id: 'expenses',
    group: 'customers_profit',
    title: 'Expenses',
    description: 'Approved expenses used in net profit calculations.',
    capability: 'partial',
    limitationMessage: 'Expense reliability depends on the upstream expense approval source.',
    supportedFilters: commonFilters,
    kpiKeys: ['approvedExpenses', 'netProfit'],
    breakdownKey: 'expenses',
    exportLabel: 'Expenses',
  },
  {
    id: 'cash-drawer-reconciliation',
    group: 'payments',
    title: 'Cash Drawer Reconciliation',
    description: 'Expected cash and closing cash reconciliation with settlement status.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: commonFilters,
    kpiKeys: ['openingCash', 'cashReceived', 'expectedCash', 'cashDifference', 'varianceStatus', 'settlementCounts'],
  },
  {
    id: 'shift-settlement-report',
    group: 'payments',
    title: 'Shift Settlement Report',
    description: 'Manager settlement overview — approved, rejected, and pending shift settlements with variance classification, reviewer info, and timeline.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: commonFilters,
    kpiKeys: ['openingCash', 'cashReceived', 'cashDifference', 'settlementCounts', 'settlementVarianceClassifications'],
    exportLabel: 'Shift Settlement',
  },
  {
    id: 'refund-report',
    group: 'requires_data',
    title: 'Refund Report',
    description: 'Restaurant refunds and partial refunds.',
    capability: 'blocked',
    limitationMessage: 'Restaurant-specific refund and partial-refund records are not stored.',
    supportedFilters: [...commonFilters, 'paymentMethod', 'customerSearch'],
    kpiKeys: [],
    breakdownKey: 'refunds',
    exportLabel: 'Refund Report',
  },
  {
    id: 'staff-cashier-performance',
    group: 'requires_data',
    title: 'Staff/Cashier Performance',
    description: 'Sales and collection by cashier or staff member.',
    capability: 'blocked',
    limitationMessage: 'Cashier/staff identity is not stored on current Restaurant report rows.',
    supportedFilters: [...commonFilters, 'paymentMethod', 'orderType'],
    kpiKeys: [],
    breakdownKey: 'staffPerformance',
    exportLabel: 'Staff/Cashier Performance',
  },
  {
    id: 'business-intelligence',
    group: 'overview',
    title: 'Business Intelligence',
    description: 'Advanced analytics: trends, product intelligence, customer segmentation, sales forecast, smart alerts, and executive dashboard with health scoring.',
    capability: 'ready',
    limitationMessage: '',
    supportedFilters: commonFilters,
    kpiKeys: ['grossSales', 'netSales', 'collectedAmount', 'netProfit', 'averageOrderValue'],
    breakdownKey: 'businessIntelligence',
    exportLabel: 'Business Intelligence',
  },
]

export function restaurantReportById(id) {
  return RESTAURANT_REPORT_DEFINITIONS.find((report) => report.id === id) || RESTAURANT_REPORT_DEFINITIONS[0]
}

export function restaurantReportsByGroup(groupId) {
  return RESTAURANT_REPORT_DEFINITIONS.filter((report) => report.group === groupId)
}
