import QRCode from 'qrcode'

function esc(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  })[char])
}

function downloadText(filename, content, type) {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

export function buildReportId(prefix = 'RPT') {
  const cleanPrefix = String(prefix || 'RPT').trim().toUpperCase().replace(/[^A-Z0-9-]/g, '') || 'RPT'
  return `${cleanPrefix}-${new Date().toISOString().slice(0, 10).replaceAll('-', '')}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`
}

export function exportReportCsv(report) {
  const rows = [
    ['Report ID', report.reportId],
    ['Workspace', report.workspaceName],
    ['Business Type', report.businessType],
    ['Date Range', report.dateRange],
    ['Generated By', report.generatedBy],
    ['Generated At', report.generatedAt],
    [],
    ['Summary', 'Value'],
    ...(report.summary || []).map((row) => [row.label, row.value]),
    [],
    ...(report.tables || []).flatMap((table) => [
      [table.title],
      table.columns.map((column) => column.label),
      ...(table.rows || []).map((row) => table.columns.map((column) => column.value(row))),
      [],
    ]),
  ]
  const csv = rows.map((row) => row.map((cell) => `"${String(cell ?? '').replaceAll('"', '""')}"`).join(',')).join('\n')
  downloadText(`${report.reportId}.csv`, csv, 'text/csv;charset=utf-8;')
}

export function exportReportExcel(report) {
  const summaryRows = (report.summary || []).map((row) => `<tr><td>${esc(row.label)}</td><td>${esc(row.value)}</td></tr>`).join('')
  const tables = (report.tables || []).map((table) => `
    <h2>${esc(table.title)}</h2>
    <table>
      <thead><tr>${table.columns.map((column) => `<th>${esc(column.label)}</th>`).join('')}</tr></thead>
      <tbody>${(table.rows || []).map((row) => `<tr>${table.columns.map((column) => `<td>${esc(column.value(row))}</td>`).join('')}</tr>`).join('')}</tbody>
    </table>
  `).join('')
  downloadText(
    `${report.reportId}.xls`,
    `<html><body><h1>${esc(report.title)}</h1><table>${summaryRows}</table>${tables}</body></html>`,
    'application/vnd.ms-excel;charset=utf-8;',
  )
}

export async function exportReportPdf(report) {
  const qrDataUrl = await QRCode.toDataURL(JSON.stringify(report.qrPayload), {
    errorCorrectionLevel: 'M',
    margin: 1,
    width: 132,
    color: { dark: '#0f172a', light: '#ffffff' },
  })
  const summaryRows = (report.summary || []).map((row) => `<div class="summary"><span>${esc(row.label)}</span><strong>${esc(row.value)}</strong></div>`).join('')
  const tables = (report.tables || []).map((table) => `
    <section>
      <h2>${esc(table.title)}</h2>
      <table>
        <thead><tr>${table.columns.map((column) => `<th>${esc(column.label)}</th>`).join('')}</tr></thead>
        <tbody>${(table.rows || []).map((row) => `<tr>${table.columns.map((column) => `<td>${esc(column.value(row))}</td>`).join('')}</tr>`).join('')}</tbody>
      </table>
    </section>
  `).join('')
  const win = window.open('', '_blank', 'noopener,noreferrer')
  if (!win) throw new Error('Popup blocked. Please allow popups to export PDF.')
  win.document.write(`
    <!doctype html>
    <html>
      <head>
        <title>${esc(report.reportId)}</title>
        <style>
          *{box-sizing:border-box} body{font-family:Inter,Arial,sans-serif;color:#0f172a;margin:0;padding:28px;background:#f8fafc}
          .sheet{max-width:1060px;margin:auto;background:white;border:1px solid #e2e8f0;border-radius:22px;padding:28px}
          .head{display:flex;justify-content:space-between;gap:20px;border-bottom:1px solid #e2e8f0;padding-bottom:18px}
          .brand{display:flex;gap:14px;align-items:center}.brand img.logo{width:66px;height:66px;object-fit:contain;border:1px solid #e2e8f0;border-radius:18px}
          h1{margin:0;font-size:26px}.muted{color:#64748b;font-size:12px;line-height:1.7}.qr{width:112px;height:112px}
          .grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:22px 0}.summary{border:1px solid #e2e8f0;border-radius:14px;padding:12px;background:#f8fafc}.summary span{display:block;color:#64748b;font-size:11px}.summary strong{display:block;margin-top:6px}
          h2{font-size:15px;margin:22px 0 10px} table{width:100%;border-collapse:collapse;font-size:12px} th,td{border:1px solid #e2e8f0;padding:9px;text-align:left} th{background:#f1f5f9}
          footer{margin-top:28px;border-top:1px solid #e2e8f0;padding-top:16px;display:flex;justify-content:space-between;gap:16px;color:#64748b;font-size:12px}
          .signature{min-width:220px;text-align:center;border-top:1px solid #94a3b8;padding-top:7px;color:#0f172a;font-weight:700}
          @media print{body{background:white;padding:0}.sheet{border:0;border-radius:0}button{display:none}}
        </style>
      </head>
      <body>
        <main class="sheet">
          <div class="head">
            <div class="brand">
              ${report.branding.logoUrl ? `<img class="logo" src="${esc(report.branding.logoUrl)}" alt="">` : ''}
              <div>
                <h1>${esc(report.title)}</h1>
                <div class="muted">${esc(report.branding.businessName)}<br>${esc(report.branding.address)}<br>${esc(report.branding.phone)} ${esc(report.branding.email)}</div>
              </div>
            </div>
            <div style="text-align:right">
              <img class="qr" src="${qrDataUrl}" alt="Report QR">
              <div class="muted">Report ID<br><strong>${esc(report.reportId)}</strong></div>
            </div>
          </div>
          <div class="muted" style="margin-top:14px">
            Workspace: ${esc(report.workspaceName)} | Module: ${esc(report.businessType)} | Range: ${esc(report.dateRange)} | Generated by: ${esc(report.generatedBy)} | Generated at: ${esc(report.generatedAt)}
          </div>
          <div class="grid">${summaryRows}</div>
          ${tables}
          <footer>
            <span>${esc(report.branding.receiptFooter || 'Powered by Nexora Solutions')}</span>
            <span class="signature">${report.branding.signatureUrl ? `<img src="${esc(report.branding.signatureUrl)}" style="max-height:42px;display:block;margin:0 auto 6px">` : ''}Authorized Signature</span>
          </footer>
        </main>
        <script>window.onload=function(){setTimeout(function(){window.print()},150)}</script>
      </body>
    </html>
  `)
  win.document.close()
}
