import { reportFileName, safePrintText } from './printDocuments.js'

function esc(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  })[char])
}

function downloadText(filename, content, type) {
  const blob = new Blob([content], { type })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  link.remove()
  URL.revokeObjectURL(url)
}

export function buildReportId(prefix = 'RPT') {
  const cleanPrefix = String(prefix || 'RPT').trim().toUpperCase().replace(/[^A-Z0-9-]/g, '') || 'RPT'
  return `${cleanPrefix}-${new Date().toISOString().slice(0, 10).replaceAll('-', '')}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`
}

export function exportReportCsv(report) {
  const rows = [
    ['Report ID', report.reportId],
    ['Workspace', report.workspaceName],
    ['Business Type', report.businessType],
    ['Date Range', report.dateRange],
    ['Generated By', report.generatedBy],
    ['Generated At', report.generatedAt],
    [],
    ['Summary', 'Value'],
    ...(report.summary || []).map((row) => [row.label, row.value]),
    [],
    ...(report.tables || []).flatMap((table) => [
      [table.title],
      table.columns.map((column) => column.label),
      ...(table.rows || []).map((row) => table.columns.map((column) => column.value(row))),
      [],
    ]),
  ]
  const csv = rows.map((row) => row.map((cell) => `"${String(cell ?? '').replaceAll('"', '""')}"`).join(',')).join('\n')
  downloadText(`${report.reportId}.csv`, csv, 'text/csv;charset=utf-8;')
}

export function exportReportExcel(report) {
  const summaryRows = (report.summary || []).map((row) => `<tr><td>${esc(row.label)}</td><td>${esc(row.value)}</td></tr>`).join('')
  const tables = (report.tables || []).map((table) => `
    <h2>${esc(table.title)}</h2>
    <table>
      <thead><tr>${table.columns.map((column) => `<th>${esc(column.label)}</th>`).join('')}</tr></thead>
      <tbody>${(table.rows || []).map((row) => `<tr>${table.columns.map((column) => `<td>${esc(column.value(row))}</td>`).join('')}</tr>`).join('')}</tbody>
    </table>
  `).join('')
  downloadText(
    `${report.reportId}.xls`,
    `<html><body><h1>${esc(report.title)}</h1><table>${summaryRows}</table>${tables}</body></html>`,
    'application/vnd.ms-excel;charset=utf-8;',
  )
}

function reportCellValue(column, row) {
  try {
    return typeof column.value === 'function' ? column.value(row) : row?.[column.key]
  } catch {
    return ''
  }
}

function addDataUrlImage(doc, dataUrl, x, y, width, height) {
  if (!dataUrl || !String(dataUrl).startsWith('data:image')) return false
  try {
    doc.addImage(dataUrl, 'PNG', x, y, width, height)
    return true
  } catch {
    return false
  }
}

async function loadReportPdfDeps() {
  const [{ default: QRCode }, { jsPDF }, autoTableModule] = await Promise.all([
    import('qrcode'),
    import('jspdf'),
    import('jspdf-autotable'),
  ])
  return { QRCode, jsPDF, autoTable: autoTableModule.default }
}

export async function exportReportPdf(report) {
  const { QRCode, jsPDF, autoTable } = await loadReportPdfDeps()
  const qrDataUrl = await QRCode.toDataURL(JSON.stringify(report.qrPayload), {
    errorCorrectionLevel: 'M',
    margin: 1,
    width: 132,
    color: { dark: '#0f172a', light: '#ffffff' },
  })
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 40
  const branding = report.branding || {}

  addDataUrlImage(doc, branding.logoUrl || branding.logo, margin, 38, 44, 44)
  doc.addImage(qrDataUrl, 'PNG', pageWidth - margin - 72, 38, 72, 72)

  doc.setTextColor('#0f172a')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text(safePrintText(report.title, 'Workspace Report'), margin, 54)
  doc.setFontSize(11)
  doc.text(safePrintText(report.workspaceName, 'Workspace'), margin, 76)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor('#475569')
  doc.text(`Report ID: ${safePrintText(report.reportId)}\nGenerated at: ${safePrintText(report.generatedAt)}`, pageWidth - margin, 124, { align: 'right' })

  autoTable(doc, {
    startY: 128,
    margin: { left: margin, right: margin },
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 9, cellPadding: 6, textColor: '#0f172a', lineColor: '#e2e8f0', lineWidth: 0.5 },
    headStyles: { fillColor: '#f1f5f9', textColor: '#334155', fontStyle: 'bold' },
    head: [['Workspace', 'Business Type', 'Date Range', 'Generated By']],
    body: [[
      safePrintText(report.workspaceName),
      safePrintText(report.businessType),
      safePrintText(report.dateRange),
      safePrintText(report.generatedBy),
    ]],
  })

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 16,
    margin: { left: margin, right: margin },
    theme: 'grid',
    styles: { font: 'helvetica', fontSize: 9, cellPadding: 6, textColor: '#0f172a', lineColor: '#e2e8f0', lineWidth: 0.5 },
    headStyles: { fillColor: '#f1f5f9', textColor: '#334155', fontStyle: 'bold' },
    head: [['Summary', 'Value', 'Summary', 'Value']],
    body: Array.from({ length: Math.ceil((report.summary || []).length / 2) || 1 }, (_, index) => {
      const left = (report.summary || [])[index * 2]
      const right = (report.summary || [])[index * 2 + 1]
      return [
        safePrintText(left?.label, ''),
        safePrintText(left?.value, ''),
        safePrintText(right?.label, ''),
        safePrintText(right?.value, ''),
      ]
    }),
  })

  let startY = doc.lastAutoTable.finalY + 18
  ;(report.tables || []).forEach((table) => {
    const columns = table.columns || []
    if (startY > pageHeight - 120) {
      doc.addPage()
      startY = margin
    }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor('#0f172a')
    doc.text(safePrintText(table.title, 'Data Table'), margin, startY)

    autoTable(doc, {
      startY: startY + 8,
      margin: { left: margin, right: margin },
      theme: 'grid',
      styles: { font: 'helvetica', fontSize: 8, cellPadding: 5, textColor: '#0f172a', lineColor: '#e2e8f0', lineWidth: 0.5, overflow: 'linebreak' },
      headStyles: { fillColor: '#f1f5f9', textColor: '#334155', fontStyle: 'bold' },
      head: [columns.map((column) => safePrintText(column.label))],
      body: (table.rows || []).map((row) => columns.map((column) => safePrintText(reportCellValue(column, row), ''))),
    })
    startY = doc.lastAutoTable.finalY + 18
  })

  const pageCount = doc.getNumberOfPages()
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page)
    doc.setDrawColor('#e2e8f0')
    doc.line(margin, pageHeight - 40, pageWidth - margin, pageHeight - 40)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor('#64748b')
    doc.text(safePrintText(branding.receiptFooter, 'Powered by Nexora Solutions'), margin, pageHeight - 24)
    doc.text(`Page ${page} of ${pageCount}`, pageWidth - margin, pageHeight - 24, { align: 'right' })
  }

  doc.save(reportFileName(report))
}
