/**
 * Copy for every Nexora marketing / automation email, as plain data.
 * marketingEmailLayout.js turns each spec into the final HTML + text.
 *
 * Duplicated on purpose in src/lib/marketingTemplateSpecs.js (admin template
 * picker); a test fails if the two copies differ. Only {{name}} and
 * {{unsubscribe}} placeholders are used, so no extra personalisation is needed.
 */
const WORKSPACE = 'https://nexorasolution.online/workspace'
const UPGRADE = 'https://nexorasolution.online/upgrade-business'
const CONTACT = 'https://nexorasolution.online/contact'

export const TEMPLATE_SPECS = [
  // ----------------------------------------------------------- automation
  {
    id: 'welcome',
    name: 'Welcome email',
    group: 'Automation',
    subject: 'Welcome to Nexora, {{name}}',
    preheader: 'Your 30 day free trial is active. Here is how to start.',
    eyebrow: 'Welcome',
    title: 'Your Nexora workspace is ready',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Thank you for joining Nexora. Your <b>30 day free trial</b> is active, so you can try every module with your own data before you decide anything.</p><p style="margin:0 0 8px;">A good first session takes about 10 minutes:</p>',
    bullets: ['Complete your business profile', 'Add your first customer or product', 'Create a sample invoice', 'Open Reports to see it all in one place'],
    ctaText: 'Open my workspace',
    ctaUrl: WORKSPACE,
    outro: 'Stuck anywhere? Reply to this email and a real person will help you set up.',
  },
  {
    id: 'trial_7_days',
    name: 'Trial: 7 days left',
    group: 'Automation',
    subject: '{{name}}, your Nexora trial ends in 7 days',
    preheader: 'One week left to try every module.',
    eyebrow: 'Trial reminder',
    title: 'You have 7 days left in your trial',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">A quick heads up: your Nexora free trial ends in <b>7 days</b>. There is still plenty of time to see if it fits your business.</p><p style="margin:0 0 8px;">If you have not yet, this week is a good time to:</p>',
    bullets: ['Enter your real products or services', 'Create a few invoices and share one with a customer', 'Invite a team member and set their access', 'Check the daily and monthly reports'],
    ctaText: 'Continue my trial',
    ctaUrl: WORKSPACE,
    outro: 'Need a hand or a demo? Reply to this email and we will set it up with you.',
  },
  {
    id: 'trial_3_days',
    name: 'Trial: 3 days left',
    group: 'Automation',
    subject: '3 days left on your Nexora trial',
    preheader: 'Choose a plan so your work stays safe and active.',
    eyebrow: 'Trial reminder',
    title: 'Only 3 days left',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Your Nexora trial ends in <b>3 days</b>. To keep your workspace and everything you entered, choose a plan before it ends.</p><p style="margin:0 0 8px;">When you upgrade:</p>',
    bullets: ['All your data stays exactly where it is', 'No setup again, you carry on from today', 'You pick the modules and plan that fit your business'],
    ctaText: 'See plans and upgrade',
    ctaUrl: UPGRADE,
    outro: 'Not sure which plan? Reply with your business type and we will suggest one.',
  },
  {
    id: 'trial_1_day',
    name: 'Trial: last day',
    group: 'Automation',
    subject: 'Last day of your Nexora trial',
    preheader: 'Your trial ends tomorrow. Keep your workspace active.',
    eyebrow: 'Final reminder',
    title: 'Your trial ends tomorrow',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">This is the last reminder: your Nexora free trial ends <b>tomorrow</b>. Upgrade today and your workspace continues without any interruption.</p>',
    bullets: ['Your customers, invoices and reports stay safe', 'Upgrade takes about two minutes'],
    ctaText: 'Upgrade now',
    ctaUrl: UPGRADE,
    outro: 'Need more time to decide? Reply to this email and tell us what you still want to test.',
  },
  {
    id: 'trial_ended',
    name: 'Trial ended',
    group: 'Automation',
    subject: '{{name}}, your Nexora trial has ended',
    preheader: 'Your data is safe. Upgrade to continue where you left off.',
    eyebrow: 'Trial ended',
    title: 'Your trial has ended, your data is safe',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Your free trial is over, but your workspace and everything you entered are still saved. Choose a plan and you can carry on exactly where you stopped.</p>',
    bullets: ['No need to enter anything again', 'Pick only the modules your business needs', 'We can help you move your daily work over'],
    ctaText: 'Choose a plan',
    ctaUrl: UPGRADE,
    outro: 'If Nexora was not the right fit, we would love to hear why. Just reply, it helps us improve.',
  },
  // ------------------------------------------------------------ campaigns
  {
    id: 'lead_nurture',
    name: 'Lead follow-up',
    group: 'Automation',
    subject: 'Still exploring business software? Nexora can help',
    preheader: 'We can help you choose the right module and set it up.',
    eyebrow: 'Thanks for your interest',
    title: 'Turn your interest into a working system',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Thank you for checking out Nexora. Choosing business software is a big decision, so here is how we make it easier:</p>',
    bullets: ['Tell us your business type and we suggest the right module', 'We help set up your workspace and first invoices', 'Start with a 30 day free trial, no commitment'],
    ctaText: 'Talk to Nexora',
    ctaUrl: CONTACT,
    outro: 'Prefer WhatsApp or a call? Reply with a good time and we will reach out.',
  },
  {
    id: 'restaurant_promo',
    name: 'Restaurant POS promotion',
    group: 'Promotion',
    subject: 'Run your restaurant smarter with Nexora Restaurant POS',
    preheader: 'Tables, KOT, takeaway and billing on one screen.',
    eyebrow: 'Restaurant POS',
    title: 'Faster orders. Happier guests.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 8px;">Manage your whole restaurant from one screen with <b>Nexora Restaurant POS</b>:</p>',
    bullets: ['Dine-in, takeaway and delivery orders', 'Table management and kitchen order tickets (KOT)', 'Fast billing, discounts and daily sales reports'],
    ctaText: 'Start free trial',
    ctaUrl: 'https://nexorasolution.online',
  },
  {
    id: 'transport_promo',
    name: 'Transport ERP promotion',
    group: 'Promotion',
    subject: 'Fleet, bookings and payments in one place with Nexora Transport',
    preheader: 'Vehicles, drivers, bookings and payments, organised.',
    eyebrow: 'Transport and Rental',
    title: 'Command your entire fleet',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 8px;"><b>Nexora Transport ERP</b> replaces notebooks and spreadsheets with one system:</p>',
    bullets: ['Vehicles, drivers and bookings in one place', 'Track payments and what each customer owes', 'Clear reports on income and expenses per vehicle'],
    ctaText: 'Explore Transport ERP',
    ctaUrl: 'https://nexorasolution.online',
  },
  {
    id: 'crm_promo',
    name: 'CRM promotion',
    group: 'Promotion',
    subject: 'Close more deals with Nexora CRM',
    preheader: 'Every lead, deal and follow-up in one pipeline.',
    eyebrow: 'Nexora CRM',
    title: 'Every lead, deal and follow-up, organised',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 8px;">With <b>Nexora CRM</b> your sales team never loses track of a customer:</p>',
    bullets: ['Capture leads from your website and WhatsApp', 'See every deal in a simple pipeline', 'Get reminders so no follow-up is missed', 'Send invoices straight from the deal'],
    ctaText: 'Try Nexora CRM',
    ctaUrl: 'https://nexorasolution.online',
  },
  {
    id: 'school_promo',
    name: 'School ERP promotion',
    group: 'Promotion',
    subject: 'Run your school effortlessly with Nexora School ERP',
    preheader: 'Admissions, fees, attendance and reports in one workspace.',
    eyebrow: 'School ERP',
    title: 'Fees, students, staff and reports, handled',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 8px;"><b>Nexora School ERP</b> keeps the whole school in one secure workspace:</p>',
    bullets: ['Admissions and student records', 'Fee collection with clear dues and receipts', 'Attendance, results and staff management'],
    ctaText: 'See School ERP',
    ctaUrl: 'https://nexorasolution.online',
  },
  {
    id: 'property_promo',
    name: 'Property ERP promotion',
    group: 'Promotion',
    subject: 'Manage properties, contracts and payments with Nexora',
    preheader: 'Tenants, contracts, maintenance and rent in one place.',
    eyebrow: 'Property ERP',
    title: 'Property operations in one place',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 8px;"><b>Nexora Property ERP</b> replaces scattered files and spreadsheets:</p>',
    bullets: ['Tenants, units and contracts', 'Rent invoices and payment tracking', 'Maintenance requests and history'],
    ctaText: 'Explore Property ERP',
    ctaUrl: 'https://nexorasolution.online/solutions/property',
  },
  // ------------------------------------------------------------- reminders
  {
    id: 'trial_reminder',
    name: 'Trial reminder',
    group: 'Reminder',
    subject: 'Your Nexora free trial is waiting',
    preheader: 'Pick up where you left off.',
    eyebrow: 'Your trial',
    title: 'Pick up where you left off',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Your Nexora trial is still active. Finish setting up your workspace and try every module before it ends.</p>',
    ctaText: 'Resume my trial',
    ctaUrl: WORKSPACE,
  },
  {
    id: 'trial_activation',
    name: 'Trial activation guide',
    group: 'Reminder',
    subject: 'Your Nexora trial setup checklist',
    preheader: 'Four quick steps to see real value from your trial.',
    eyebrow: 'Getting started',
    title: 'Get value from your trial today',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 8px;">These four steps show how Nexora fits your business:</p>',
    bullets: ['Complete your profile', 'Add your first customer', 'Create a sample invoice', 'Open the reports'],
    ctaText: 'Open workspace',
    ctaUrl: WORKSPACE,
  },
  {
    id: 'inactive_trial',
    name: 'Inactive trial winback',
    group: 'Reminder',
    subject: 'Need help finishing your Nexora setup?',
    preheader: 'We can set it up with you.',
    eyebrow: 'We can help',
    title: 'Let us set it up with you',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Your trial is still available. If setup felt busy, reply to this email and our team will guide you through module choice, staff access and your first invoice and report.</p>',
    ctaText: 'Resume setup',
    ctaUrl: WORKSPACE,
  },
  {
    id: 'payment_reminder',
    name: 'Payment reminder',
    group: 'Reminder',
    subject: 'Friendly reminder: your Nexora payment is due',
    preheader: 'Renew to avoid any interruption.',
    eyebrow: 'Billing',
    title: 'Keep your workspace active',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">This is a friendly reminder that a payment is due on your Nexora account. Renew now to avoid any interruption.</p>',
    ctaText: 'Make payment',
    ctaUrl: UPGRADE,
  },
  {
    id: 'client_upgrade',
    name: 'Client upgrade offer',
    group: 'Reminder',
    subject: 'Unlock more Nexora modules for your business',
    preheader: 'More modules, advanced reports and priority support.',
    eyebrow: 'Grow with Nexora',
    title: 'Scale beyond one workflow',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 8px;">Your workspace can grow with:</p>',
    bullets: ['Extra modules for more of your operations', 'Advanced reports', 'Staff controls', 'Priority support'],
    ctaText: 'View upgrade options',
    ctaUrl: UPGRADE,
  },
  {
    id: 'support_checkin',
    name: 'Customer success check-in',
    group: 'Reminder',
    subject: 'How is your Nexora workspace going?',
    preheader: 'A quick check-in from the Nexora team.',
    eyebrow: 'Check-in',
    title: 'A quick check-in from Nexora',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">We wanted to check that your workspace is running smoothly. If you need help with reports, staff permissions, invoices or module setup, our team is ready to help.</p>',
    ctaText: 'Contact support',
    ctaUrl: CONTACT,
  },
]
