/**
 * Copy for every Nexora marketing / automation email, as plain data.
 * marketingEmailLayout.js turns each spec into the final HTML + text.
 *
 * Duplicated on purpose in src/lib/marketingTemplateSpecs.js (admin template
 * picker); a test fails if the two copies differ. Only {{name}} and
 * {{unsubscribe}} placeholders are used, so no extra personalisation is needed.
 */
const WORKSPACE = 'https://nexorasolution.online/workspace'
const UPGRADE = 'https://nexorasolution.online/upgrade-business'
const CONTACT = 'https://nexorasolution.online/contact'

export const TEMPLATE_SPECS = [
  // ----------------------------------------------------------- automation
  {
    id: 'welcome',
    name: 'Welcome email',
    group: 'Automation',
    subject: 'Welcome to Nexora, your workspace is ready',
    preheader: 'Your 30 day free trial is active. Here is how to start.',
    eyebrow: 'Welcome',
    title: 'Your Nexora workspace is ready',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Thank you for joining Nexora. Your <b>30 day free trial</b> is active, so you can try every module with your own data before you decide anything.</p><p style="margin:0 0 8px;">A good first session takes about 10 minutes:</p>',
    bullets: ['Complete your business profile', 'Add your first customer or product', 'Create a sample invoice', 'Open Reports to see it all in one place'],
    ctaText: 'Open my workspace',
    ctaUrl: WORKSPACE,
    outro: 'Stuck anywhere? Reply to this email and a real person will help you set up.',
  },
  {
    id: 'trial_7_days',
    name: 'Trial: 7 days left',
    group: 'Automation',
    subject: 'Your Nexora trial ends in 7 days',
    preheader: 'One week left to try every module.',
    eyebrow: 'Trial reminder',
    title: 'You have 7 days left in your trial',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">A quick heads up: your Nexora free trial ends in <b>7 days</b>. There is still plenty of time to see if it fits your business.</p><p style="margin:0 0 8px;">If you have not yet, this week is a good time to:</p>',
    bullets: ['Enter your real products or services', 'Create a few invoices and share one with a customer', 'Invite a team member and set their access', 'Check the daily and monthly reports'],
    ctaText: 'Continue my trial',
    ctaUrl: WORKSPACE,
    outro: 'Need a hand or a demo? Reply to this email and we will set it up with you.',
  },
  {
    id: 'trial_3_days',
    name: 'Trial: 3 days left',
    group: 'Automation',
    subject: '3 days left on your Nexora trial',
    preheader: 'Choose a plan so your work stays safe and active.',
    eyebrow: 'Trial reminder',
    title: 'Only 3 days left',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Your Nexora trial ends in <b>3 days</b>. To keep your workspace and everything you entered, choose a plan before it ends.</p><p style="margin:0 0 8px;">When you upgrade:</p>',
    bullets: ['All your data stays exactly where it is', 'No setup again, you carry on from today', 'You pick the modules and plan that fit your business'],
    ctaText: 'See plans and upgrade',
    ctaUrl: UPGRADE,
    outro: 'Not sure which plan? Reply with your business type and we will suggest one.',
  },
  {
    id: 'trial_1_day',
    name: 'Trial: last day',
    group: 'Automation',
    subject: 'Last day of your Nexora trial',
    preheader: 'Your trial ends tomorrow. Keep your workspace active.',
    eyebrow: 'Final reminder',
    title: 'Your trial ends tomorrow',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">This is the last reminder: your Nexora free trial ends <b>tomorrow</b>. Upgrade today and your workspace continues without any interruption.</p>',
    bullets: ['Your customers, invoices and reports stay safe', 'Upgrade takes about two minutes'],
    ctaText: 'Upgrade now',
    ctaUrl: UPGRADE,
    outro: 'Need more time to decide? Reply to this email and tell us what you still want to test.',
  },
  {
    id: 'trial_ended',
    name: 'Trial ended',
    group: 'Automation',
    subject: 'Your Nexora trial has ended, your data is safe',
    preheader: 'Your data is safe. Upgrade to continue where you left off.',
    eyebrow: 'Trial ended',
    title: 'Your trial has ended, your data is safe',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Your free trial is over, but your workspace and everything you entered are still saved. Choose a plan and you can carry on exactly where you stopped.</p>',
    bullets: ['No need to enter anything again', 'Pick only the modules your business needs', 'We can help you move your daily work over'],
    ctaText: 'Choose a plan',
    ctaUrl: UPGRADE,
    outro: 'If Nexora was not the right fit, we would love to hear why. Just reply, it helps us improve.',
  },
  // ------------------------------------------------------------ campaigns
  {
    id: 'lead_nurture',
    name: 'Lead follow-up',
    group: 'Automation',
    subject: 'Still exploring business software? Nexora can help',
    preheader: 'We can help you choose the right module and set it up.',
    eyebrow: 'Thanks for your interest',
    title: 'Turn your interest into a working system',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Thank you for checking out Nexora. Choosing business software is a big decision, so here is how we make it easier:</p>',
    bullets: ['Tell us your business type and we suggest the right module', 'We help set up your workspace and first invoices', 'Start with a 30 day free trial, no commitment'],
    ctaText: 'Talk to Nexora',
    ctaUrl: CONTACT,
    outro: 'Prefer WhatsApp or a call? Reply with a good time and we will reach out.',
  },
  {
    id: 'restaurant_promo',
    name: 'Restaurant POS promotion',
    group: 'Promotion',
    subject: 'Faster tables, happier guests: Nexora Restaurant POS',
    preheader: 'Dine-in, takeaway, KOT and billing on one screen.',
    modern: true,
    eyebrow: 'Restaurant POS',
    title: 'Faster orders. Happier guests.',
    subtitle: 'One screen for tables, kitchen and billing.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Your staff should spend time serving guests, not writing bills. <b>Nexora Restaurant POS</b> puts every order, table and kitchen ticket in one place.</p>',
    stats: [{ value: '1 screen', label: 'orders to bill' }, { value: 'KOT', label: 'to the kitchen' }, { value: 'Daily', label: 'sales reports' }],
    features: [
      { title: 'Dine-in, takeaway, delivery', text: 'Take every kind of order from the same screen.' },
      { title: 'Table management', text: 'See which tables are free, busy or waiting for the bill.' },
      { title: 'Kitchen order tickets', text: 'Orders reach the kitchen instantly, with fewer mistakes.' },
      { title: 'Fast billing', text: 'Discounts, split bills and receipts in a few taps.' },
    ],
    callout: 'Free trial, no card needed. Set up your menu and print your first bill today.',
    ctaText: 'Start free trial',
    ctaUrl: 'https://nexorasolution.online',
    secondaryText: 'See Restaurant POS',
    secondaryUrl: 'https://nexorasolution.online/solutions/pos',
    accent: '#ea580c',
    accent2: '#f59e0b',
  },
  {
    id: 'transport_promo',
    name: 'Transport ERP promotion',
    group: 'Promotion',
    subject: 'Fleet, bookings and payments in one place with Nexora Transport',
    preheader: 'Vehicles, drivers, bookings and payments, organised.',
    modern: true,
    eyebrow: 'Transport and Rental',
    title: 'Command your entire fleet',
    subtitle: 'Stop chasing notebooks and spreadsheets.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Know where every vehicle, driver and rupee is. <b>Nexora Transport ERP</b> replaces paper registers with one clear system.</p>',
    stats: [{ value: 'All', label: 'vehicles in one list' }, { value: 'Live', label: 'dues per customer' }, { value: 'Per vehicle', label: 'income and cost' }],
    features: [
      { title: 'Vehicles and drivers', text: 'Keep records, documents and assignments together.' },
      { title: 'Bookings', text: 'Create, confirm and track every booking.' },
      { title: 'Payments and dues', text: 'See what each customer has paid and still owes.' },
      { title: 'Clear reports', text: 'Income and expenses for every vehicle, any month.' },
    ],
    callout: 'Most fleets save hours every week once bookings and payments live in one place.',
    ctaText: 'Explore Transport ERP',
    ctaUrl: 'https://nexorasolution.online',
    secondaryText: 'See how it works',
    secondaryUrl: 'https://nexorasolution.online/contact',
    accent: '#0f766e',
    accent2: '#0ea5e9',
  },
  {
    id: 'crm_promo',
    name: 'CRM promotion',
    group: 'Promotion',
    subject: 'Close more deals with Nexora CRM',
    preheader: 'Every lead, deal and follow-up in one pipeline.',
    modern: true,
    eyebrow: 'Nexora CRM',
    title: 'Never lose a lead again',
    subtitle: 'Every lead, deal and follow-up in one pipeline.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Leads go cold when follow-ups slip. <b>Nexora CRM</b> keeps your whole sales team on the same page.</p>',
    stats: [{ value: '1 pipeline', label: 'for every deal' }, { value: 'Auto', label: 'follow-up reminders' }, { value: '0', label: 'leads lost' }],
    features: [
      { title: 'Capture leads', text: 'From your website, forms and WhatsApp chats.' },
      { title: 'Visual pipeline', text: 'Drag deals from first contact to closed.' },
      { title: 'Smart reminders', text: 'Know exactly who to call today.' },
      { title: 'Invoices from deals', text: 'Turn a won deal into an invoice in one click.' },
    ],
    callout: 'Switch it on today and your next lead is tracked from the first message.',
    ctaText: 'Try Nexora CRM',
    ctaUrl: 'https://nexorasolution.online',
    secondaryText: 'Learn more',
    secondaryUrl: 'https://nexorasolution.online/solutions/crm',
    accent: '#4f46e5',
    accent2: '#7c3aed',
  },
  {
    id: 'school_promo',
    name: 'School ERP promotion',
    group: 'Promotion',
    subject: 'Run your school effortlessly with Nexora School ERP',
    preheader: 'Admissions, fees, attendance and reports in one workspace.',
    modern: true,
    eyebrow: 'School ERP',
    title: 'Fees, students and staff, handled',
    subtitle: 'Your whole school in one secure workspace.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Less paperwork, fewer fee disputes, clearer reports. <b>Nexora School ERP</b> helps your office run on time.</p>',
    stats: [{ value: 'Fees', label: 'dues and receipts' }, { value: 'Daily', label: 'attendance' }, { value: 'Results', label: 'and report cards' }],
    features: [
      { title: 'Admissions and records', text: 'Every student file in one searchable place.' },
      { title: 'Fee collection', text: 'Clear dues, instant receipts, no confusion.' },
      { title: 'Attendance and results', text: 'Mark attendance fast, publish results neatly.' },
      { title: 'Staff management', text: 'Teachers, roles and payroll organised.' },
    ],
    callout: 'Parents see accurate fee records, and your office sees who still needs a reminder.',
    ctaText: 'See School ERP',
    ctaUrl: 'https://nexorasolution.online',
    secondaryText: 'Learn more',
    secondaryUrl: 'https://nexorasolution.online/solutions/school-erp',
    accent: '#1d4ed8',
    accent2: '#06b6d4',
  },
  {
    id: 'property_promo',
    name: 'Property ERP promotion',
    group: 'Promotion',
    subject: 'Manage properties, contracts and payments with Nexora',
    preheader: 'Tenants, contracts, maintenance and rent in one place.',
    modern: true,
    eyebrow: 'Property ERP',
    title: 'Property operations in one place',
    subtitle: 'Tenants, units, rent and repairs under control.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Missed rent and lost contracts cost real money. <b>Nexora Property ERP</b> gives you one clean record of everything.</p>',
    stats: [{ value: 'Every', label: 'unit and tenant' }, { value: 'Auto', label: 'rent invoices' }, { value: 'Full', label: 'repair history' }],
    features: [
      { title: 'Tenants and contracts', text: 'Dates, terms and documents together.' },
      { title: 'Rent invoices', text: 'Generate invoices and track who has paid.' },
      { title: 'Maintenance requests', text: 'Log, assign and close repairs with history.' },
      { title: 'Owner reports', text: 'Income and expenses per property.' },
    ],
    callout: 'Know which units are vacant and which rents are late in seconds.',
    ctaText: 'Explore Property ERP',
    ctaUrl: 'https://nexorasolution.online/solutions/property-erp',
    secondaryText: 'Talk to our team',
    secondaryUrl: 'https://nexorasolution.online/contact',
    accent: '#7c2d12',
    accent2: '#d97706',
  },
  {
    id: 'tools_hub_promo',
    name: 'Free tools: all tools',
    group: 'Free tools',
    subject: 'Free business tools from Nexora, no sign-up needed',
    preheader: 'Invoices, quotations and receipts in minutes. Free.',
    modern: true,
    eyebrow: 'Free tools',
    title: 'Free tools for your business',
    subtitle: 'Create professional documents in minutes.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">You do not need an account or a credit card. Open a tool, fill in the details and download a clean, professional document.</p>',
    stats: [{ value: 'Free', label: 'no card needed' }, { value: '2 min', label: 'to your first invoice' }, { value: 'PDF', label: 'ready to send' }],
    features: [
      { title: 'Invoice generator', text: 'Branded invoices with tax, totals and your logo.' },
      { title: 'Quotation generator', text: 'Win more work with a neat, clear quote.' },
      { title: 'Thermal receipt', text: 'Receipts sized for 58 mm and 80 mm printers.' },
      { title: 'Invoice on letterhead', text: 'Print on your own company letterhead.' },
    ],
    callout: 'Like the tools? Nexora can save every invoice and customer for you automatically.',
    ctaText: 'Open free tools',
    ctaUrl: 'https://nexorasolution.online/tools',
    secondaryText: 'Try Nexora free',
    secondaryUrl: 'https://nexorasolution.online',
    accent: '#4f46e5',
    accent2: '#2563eb',
  },
  {
    id: 'invoice_tool_promo',
    name: 'Free tool: Invoice generator',
    group: 'Free tools',
    subject: 'Make a professional invoice in 2 minutes, free',
    preheader: 'Free invoice generator, no sign-up.',
    modern: true,
    eyebrow: 'Free invoice generator',
    title: 'Professional invoices, free',
    subtitle: 'No sign-up. No watermark. Download and send.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Still making invoices in Word or Excel? Try the <b>Nexora Invoice Generator</b> and get a clean invoice ready to send.</p>',
    stats: [{ value: 'Free', label: 'forever' }, { value: '2 min', label: 'per invoice' }, { value: 'PDF', label: 'download' }],
    features: [
      { title: 'Your logo and details', text: 'Look professional from the first invoice.' },
      { title: 'Tax and totals', text: 'Totals and taxes are calculated for you.' },
      { title: 'Share instantly', text: 'Download a PDF or send a link.' },
      { title: 'GST, VAT and CIS versions', text: 'Pick the format your country needs.' },
    ],
    callout: 'Want invoices saved, customers remembered and payments tracked? Nexora does that too.',
    ctaText: 'Create an invoice',
    ctaUrl: 'https://nexorasolution.online/tools/invoice-generator',
    secondaryText: 'See all free tools',
    secondaryUrl: 'https://nexorasolution.online/tools',
    accent: '#059669',
    accent2: '#0ea5e9',
  },
  {
    id: 'quotation_tool_promo',
    name: 'Free tool: Quotation generator',
    group: 'Free tools',
    subject: 'Send a quotation that wins the job, free tool',
    preheader: 'Free quotation generator, no sign-up.',
    modern: true,
    eyebrow: 'Free quotation generator',
    title: 'Quotes that win the job',
    subtitle: 'Build and download a clear quotation in minutes.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">A neat quotation builds trust before you say a word. The <b>Nexora Quotation Generator</b> makes it quick.</p>',
    stats: [{ value: 'Free', label: 'to use' }, { value: 'Minutes', label: 'not hours' }, { value: 'PDF', label: 'ready' }],
    features: [
      { title: 'Itemised pricing', text: 'Quantities, rates, discounts and totals.' },
      { title: 'Your branding', text: 'Add your logo and business details.' },
      { title: 'Terms and validity', text: 'State how long your quote is valid.' },
      { title: 'Turn into an invoice', text: 'Convert accepted quotes in Nexora.' },
    ],
    callout: 'Customers decide faster when the quote is clear and professional.',
    ctaText: 'Create a quotation',
    ctaUrl: 'https://nexorasolution.online/tools/quotation-generator',
    secondaryText: 'See all free tools',
    secondaryUrl: 'https://nexorasolution.online/tools',
    accent: '#7c3aed',
    accent2: '#2563eb',
  },
  {
    id: 'receipt_tool_promo',
    name: 'Free tool: Thermal receipt generator',
    group: 'Free tools',
    subject: 'Print clean receipts for your shop, free tool',
    preheader: 'Free thermal receipt generator for 58 mm and 80 mm.',
    modern: true,
    eyebrow: 'Free receipt generator',
    title: 'Receipts that look right',
    subtitle: 'Made for 58 mm and 80 mm thermal printers.',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Shop, cafe or counter sales? The <b>Nexora Thermal Receipt Generator</b> makes receipts that print correctly the first time.</p>',
    stats: [{ value: '58/80', label: 'mm sizes' }, { value: 'Free', label: 'to use' }, { value: '1 click', label: 'print' }],
    features: [
      { title: 'Right paper size', text: 'Layouts tuned for thermal rolls.' },
      { title: 'Items and totals', text: 'Clear lines, tax and payment details.' },
      { title: 'Your shop name', text: 'Logo, address and phone on top.' },
      { title: 'Upgrade to a full POS', text: 'Move to Nexora POS when you grow.' },
    ],
    callout: 'Selling every day? Nexora POS prints receipts, tracks stock and shows daily sales.',
    ctaText: 'Make a receipt',
    ctaUrl: 'https://nexorasolution.online/tools/thermal-receipt-generator',
    secondaryText: 'See all free tools',
    secondaryUrl: 'https://nexorasolution.online/tools',
    accent: '#be123c',
    accent2: '#f97316',
  },
  // ------------------------------------------------------------- reminders
  {
    id: 'trial_reminder',
    name: 'Trial reminder',
    group: 'Reminder',
    subject: 'Your Nexora free trial is waiting',
    preheader: 'Pick up where you left off.',
    eyebrow: 'Your trial',
    title: 'Pick up where you left off',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Your Nexora trial is still active. Finish setting up your workspace and try every module before it ends.</p>',
    ctaText: 'Resume my trial',
    ctaUrl: WORKSPACE,
  },
  {
    id: 'trial_activation',
    name: 'Trial activation guide',
    group: 'Reminder',
    subject: 'Your Nexora trial setup checklist',
    preheader: 'Four quick steps to see real value from your trial.',
    eyebrow: 'Getting started',
    title: 'Get value from your trial today',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 8px;">These four steps show how Nexora fits your business:</p>',
    bullets: ['Complete your profile', 'Add your first customer', 'Create a sample invoice', 'Open the reports'],
    ctaText: 'Open workspace',
    ctaUrl: WORKSPACE,
  },
  {
    id: 'inactive_trial',
    name: 'Inactive trial winback',
    group: 'Reminder',
    subject: 'Need help finishing your Nexora setup?',
    preheader: 'We can set it up with you.',
    eyebrow: 'We can help',
    title: 'Let us set it up with you',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">Your trial is still available. If setup felt busy, reply to this email and our team will guide you through module choice, staff access and your first invoice and report.</p>',
    ctaText: 'Resume setup',
    ctaUrl: WORKSPACE,
  },
  {
    id: 'payment_reminder',
    name: 'Payment reminder',
    group: 'Reminder',
    subject: 'Friendly reminder: your Nexora payment is due',
    preheader: 'Renew to avoid any interruption.',
    eyebrow: 'Billing',
    title: 'Keep your workspace active',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">This is a friendly reminder that a payment is due on your Nexora account. Renew now to avoid any interruption.</p>',
    ctaText: 'Make payment',
    ctaUrl: UPGRADE,
  },
  {
    id: 'client_upgrade',
    name: 'Client upgrade offer',
    group: 'Reminder',
    subject: 'Unlock more Nexora modules for your business',
    preheader: 'More modules, advanced reports and priority support.',
    eyebrow: 'Grow with Nexora',
    title: 'Scale beyond one workflow',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 8px;">Your workspace can grow with:</p>',
    bullets: ['Extra modules for more of your operations', 'Advanced reports', 'Staff controls', 'Priority support'],
    ctaText: 'View upgrade options',
    ctaUrl: UPGRADE,
  },
  {
    id: 'support_checkin',
    name: 'Customer success check-in',
    group: 'Reminder',
    subject: 'How is your Nexora workspace going?',
    preheader: 'A quick check-in from the Nexora team.',
    eyebrow: 'Check-in',
    title: 'A quick check-in from Nexora',
    intro: '<p style="margin:0 0 14px;">Hi {{name}},</p><p style="margin:0 0 14px;">We wanted to check that your workspace is running smoothly. If you need help with reports, staff permissions, invoices or module setup, our team is ready to help.</p>',
    ctaText: 'Contact support',
    ctaUrl: CONTACT,
  },
]
