import Link from '../../components/AppLink.jsx'
import { useState } from 'react'
import { HiOutlineArrowRight, HiOutlineArrowLeft, HiOutlineWifi, HiOutlineCheckCircle, HiOutlineCodeBracket, HiOutlineShieldCheck, HiOutlineCog8Tooth, HiOutlineDocumentText, HiOutlineBolt, HiOutlineChatBubbleLeftRight, HiOutlineCreditCard, HiOutlineChevronDown } from 'react-icons/hi2'
import { FaWhatsapp } from 'react-icons/fa6'
import PageSeo from '../../components/PageSeo.jsx'
import { getSeoForPath } from '../../lib/seoMetadata.js'
import PublicPageShell from './PublicPageShell.jsx'
const WHATSAPP_URL = 'https://wa.me/923194329754'

const services = [
  { icon: HiOutlineCreditCard, title: 'Payment Gateways', desc: 'Stripe, PayPal, JazzCash, Easypaisa, bank APIs. Secure tokenization, webhook handling, PCI-compliant payment flows.' },
  { icon: HiOutlineChatBubbleLeftRight, title: 'WhatsApp Business API', desc: 'Send messages, templates, media. Webhook handling for incoming messages. Two-way conversation sync with your CRM/ERP.' },
  { icon: HiOutlineBolt, title: 'SMS & Email APIs', desc: 'Twilio, Vonage, SendGrid integration. Transactional and marketing messages. Delivery tracking and bounce handling.' },
  { icon: HiOutlineCog8Tooth, title: 'Legacy System Integration', desc: 'Connect modern apps with old databases, SOAP services, CSV exports. We bridge the gap without disrupting existing workflows.' },
  { icon: HiOutlineCodeBracket, title: 'REST & GraphQL APIs', desc: 'Custom API design and development. Clean RESTful endpoints, GraphQL for flexible queries, comprehensive documentation.' },
  { icon: HiOutlineShieldCheck, title: 'Authentication & SSO', desc: 'OAuth 2.0, SAML, OpenID Connect. Single sign-on across apps. Social login (Google, Facebook, Apple).' },
  { icon: HiOutlineDocumentText, title: 'Shipping & Logistics', desc: 'TCS, Leopards, DHL, FedEx APIs. Rate calculation, label printing, tracking integration, delivery confirmation.' },
  { icon: HiOutlineWifi, title: 'Real-Time Webhooks', desc: 'Event-driven architecture. Instant notifications when payments clear, orders ship, or customers sign up. Reliable retry logic.' },
]

const faqs = [
  { q: 'What is API integration and why do I need it?', a: 'API integration connects your software with external services — payment gateways, WhatsApp, SMS providers, shipping carriers, and legacy systems. Instead of manually moving data between systems, APIs automate everything in real-time. Benefits: 80% less manual data entry, zero errors, instant updates across all systems.' },
  { q: 'How long does API integration take?', a: 'Simple integration (one payment gateway): 1-2 weeks. Medium integration (multiple services): 3-6 weeks. Complex integration (legacy systems, custom APIs): 6-12 weeks.' },
  { q: 'What payment gateways do you work with?', a: 'Stripe (international), PayPal, JazzCash, Easypaisa, HBL, UBL, Meezan Bank, and any gateway with an API. We handle the entire flow — tokenization, 3D Secure, webhooks, reconciliation.' },
  { q: 'Can you integrate WhatsApp Business API?', a: 'Yes — this is one of our most requested integrations. We connect WhatsApp Business API with your CRM, sending automated messages, templates, and handling incoming webhooks. All conversations sync to your dashboard.' },
  { q: 'How do you handle errors and failures?', a: 'Every integration includes: automatic retry with exponential backoff, dead letter queues for failed messages, real-time alerts on failures, comprehensive logging, and a health dashboard showing the status of every integration.' },
  { q: 'Do you provide API documentation?', a: 'Yes — every custom API we build includes OpenAPI/Swagger documentation, usage examples, authentication guides, and rate limiting information. If we integrate a third-party API, we document the integration architecture for your team.' },
]

function FaqItem({ faq, isOpen, onToggle }) {
  return (<article className="rounded-[1.35rem] border border-slate-200 bg-white shadow-sm transition-all duration-200 hover:shadow-md"><button type="button" onClick={onToggle} className="flex w-full items-center justify-between gap-4 p-5 text-left" aria-expanded={isOpen}><h3 className="text-[14px] font-semibold text-slate-900 sm:text-[15px]">{faq.q}</h3><HiOutlineChevronDown className={`h-5 w-5 shrink-0 text-slate-400 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`} /></button><div className={`grid transition-all duration-300 ease-out ${isOpen ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'}`}><div className="overflow-hidden"><p className="px-5 pb-5 text-[13px] leading-[1.7] text-slate-500">{faq.a}</p></div></div></article>)
}

export default function APIIntegrationPage() {
  const seo = getSeoForPath('/api-integration')
  const [openFaq, setOpenFaq] = useState(0)
  return (<PublicPageShell backTo="/software-development" backLabel="Back to Software Dev" badge="API Integration" badgeIcon={HiOutlineWifi}><PageSeo {...seo} faqItems={faqs.map(f => ({ question: f.q, answer: f.a }))} /><nav aria-label="Breadcrumb" className="sr-only"><Link to="/">Home</Link><span> / </span><Link to="/software-development">Software Development</Link><span> / </span><span aria-current="page">API Integration</span></nav>
    <section className="relative overflow-hidden bg-[linear-gradient(180deg,#ffffff_0%,#eef2ff_64%,#f1f5f9_100%)] pb-14 pt-20 sm:pb-18 sm:pt-24 lg:pb-20 lg:pt-28"><div className="soft-arc-bg pointer-events-none" /><div className="relative mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><p className="mt-7 inline-flex items-center gap-1.5 rounded-full border border-indigo-200/60 bg-indigo-50/70 px-4 py-2 text-xs font-medium uppercase tracking-[0.14em] text-indigo-700 shadow-sm backdrop-blur-xl"><HiOutlineWifi className="h-3.5 w-3.5" />API Integration</p><h1 className="mt-5 max-w-4xl text-[2.5rem] font-semibold leading-[1.06] tracking-[-0.02em] text-slate-900 sm:text-[3.5rem] lg:text-[4.2rem]"><span className="bg-gradient-to-r from-indigo-600 via-blue-600 to-violet-600 bg-clip-text text-transparent">API</span> Integration</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-500 sm:text-lg">Connect your software with payment gateways, WhatsApp, SMS, shipping carriers, and legacy systems. Reliable, secure, real-time data flow.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full bg-slate-900 px-6 text-sm font-medium text-white shadow-[0_4px_16px_-6px_rgba(15,23,42,0.3)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-slate-800 active:scale-[0.97]">Discuss Integration <HiOutlineArrowRight className="text-lg" /></a><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full border border-slate-200/60 bg-white/80 px-6 text-sm font-medium text-slate-500 shadow-sm backdrop-blur-xl transition-all duration-200 hover:-translate-y-0.5 active:scale-[0.97]"><FaWhatsapp className="text-base text-emerald-500" />WhatsApp Us</a></div></div></section>
    <section data-reveal className="bg-white py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="text-center"><h2 className="text-3xl font-semibold tracking-[-0.02em] text-slate-900 sm:text-5xl">Integration <span className="bg-gradient-to-r from-indigo-600 via-blue-600 to-violet-600 bg-clip-text text-transparent">Services</span></h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map(s => (<article key={s.title} className="group flex flex-col rounded-[1.35rem] border border-slate-200/60 bg-white p-5 shadow-[0_4px_16px_-8px_rgba(15,23,42,0.05)] transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_14px_36px_-16px_rgba(15,23,42,0.16)]"><div className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-100/80 text-indigo-700 ring-1 ring-indigo-200/60 transition-transform duration-300 group-hover:scale-110"><s.icon className="h-5 w-5" /></div><h3 className="mt-3 text-[14px] font-semibold text-slate-900">{s.title}</h3><p className="mt-2 flex-1 text-[12px] leading-[1.6] text-slate-500">{s.desc}</p></article>))}</div></div></section>
    <section data-reveal className="bg-white py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-3xl px-5 sm:px-6 lg:px-8"><div className="text-center"><h2 className="text-3xl font-semibold tracking-[-0.02em] text-slate-900 sm:text-5xl">API <span className="bg-gradient-to-r from-indigo-600 via-blue-600 to-violet-600 bg-clip-text text-transparent">FAQs</span></h2></div><div className="mt-10 grid gap-3">{faqs.map((f, i) => <FaqItem key={f.q} faq={f} isOpen={openFaq === i} onToggle={() => setOpenFaq(openFaq === i ? -1 : i)} />)}</div></div></section>
    <section data-reveal className="px-5 pb-16 sm:px-6 sm:pb-20 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-6 rounded-[2rem] border border-indigo-200/60 bg-[linear-gradient(135deg,#eef2ff_0%,#ffffff_58%,#e0e7ff_100%)] p-6 shadow-md sm:p-8 lg:grid-cols-[1fr_auto]"><div><h2 className="text-3xl font-semibold tracking-tight text-slate-900 sm:text-4xl">Need to Connect Your Systems?</h2><p className="mt-3 text-sm leading-7 text-slate-500">Free consultation — we map out your integration architecture and provide a detailed plan.</p></div><div className="flex flex-col gap-3 min-[420px]:flex-row"><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full bg-indigo-600 px-6 text-sm font-medium text-white shadow-[0_4px_16px_-6px_rgba(99,102,241,0.3)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-indigo-500 active:scale-[0.97]">Get Free Quote <HiOutlineArrowRight className="text-lg" /></a><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full border border-slate-200/60 bg-white/80 px-6 text-sm font-medium text-slate-500 shadow-sm backdrop-blur-xl transition-all duration-200 hover:-translate-y-0.5 active:scale-[0.97]"><FaWhatsapp className="text-base text-emerald-500" />WhatsApp</a></div></div></section>
  </PublicPageShell>)
}
