import Link from '../../components/AppLink.jsx'
import { useState } from 'react'
import { HiOutlineArrowRight, HiOutlineArrowLeft, HiOutlineCloud, HiOutlineCheckCircle, HiOutlineServer, HiOutlineShieldCheck, HiOutlineArrowPath, HiOutlineCog8Tooth, HiOutlineGlobeAlt, HiOutlineBolt, HiOutlineCircleStack, HiOutlineChevronDown } from 'react-icons/hi2'
import { FaWhatsapp } from 'react-icons/fa6'
import PageSeo from '../../components/PageSeo.jsx'
import { getSeoForPath } from '../../lib/seoMetadata.js'
import PublicPageShell from './PublicPageShell.jsx'
const WHATSAPP_URL = 'https://wa.me/923194329754'

const services = [
  { icon: HiOutlineCloud, title: 'Cloud Migration', desc: 'Move from on-premise to cloud with zero downtime. Full data migration, DNS cutover, and rollback plan included.' },
  { icon: HiOutlineServer, title: 'Serverless Architecture', desc: 'Cloudflare Workers + Firebase — auto-scaling from 0 to millions. Pay only for what you use. No server management.' },
  { icon: HiOutlineArrowPath, title: 'CI/CD Pipelines', desc: 'Automated build, test, deploy with GitHub Actions. Every push to main goes live in minutes. Zero-downtime deployments.' },
  { icon: HiOutlineShieldCheck, title: 'Security Hardening', desc: 'DDoS protection, WAF rules, rate limiting, bot management, SSL/TLS, CSP headers — all configured on Cloudflare\'s edge.' },
  { icon: HiOutlineGlobeAlt, title: 'CDN & Edge', desc: 'Global CDN with 330+ cities. Static assets delivered in <50ms. API responses cached at edge for instant performance.' },
  { icon: HiOutlineCog8Tooth, title: 'Managed Infrastructure', desc: 'We handle DNS, SSL, backups, monitoring, alerts, scaling. You focus on your business. 24/7 infrastructure support.' },
  { icon: HiOutlineCircleStack, title: 'Database Management', desc: 'Firebase, MySQL, PostgreSQL, MongoDB — setup, migration, optimization, backups, replication, and monitoring.' },
  { icon: HiOutlineBolt, title: 'Performance Optimization', desc: 'Core Web Vitals tuning, image optimization, code splitting, cache strategy, lazy loading. Target: 95+ Lighthouse score.' },
]

const faqs = [
  { q: 'Should I use Cloudflare or AWS?', a: 'For most businesses, Cloudflare Workers + Firebase is the ideal stack — simpler, faster at edge, and dramatically cheaper at scale. AWS is better for complex enterprise needs (Kubernetes, GPU instances, VPC). We help you choose and can work with either.' },
  { q: 'How much does cloud hosting cost?', a: 'Cloudflare Workers: free tier (100K requests/day), paid from $5/month. Firebase: free tier (Spark plan), paid from $25/month (Blaze plan). A typical business app costs $25-$100/month total. We optimize for cost — most clients pay less than their previous hosting.' },
  { q: 'How long does cloud migration take?', a: 'Simple migration (static site, basic API): 1-2 weeks. Complex migration (database, microservices, CI/CD): 4-8 weeks. We provide a detailed migration plan with timeline and risk assessment before starting.' },
  { q: 'Will my site go down during migration?', a: 'No. We use blue-green deployment and DNS gradual cutover. Your old site stays live until the new setup is fully tested. Typical downtime: 0 seconds.' },
  { q: 'Do you provide ongoing management?', a: 'Yes — our managed infrastructure plans include 24/7 monitoring, automatic backups, security patches, SSL renewal, performance optimization, and emergency response. Plans start at PKR 15,000/month.' },
]

function FaqItem({ faq, isOpen, onToggle }) {
  return (<article className="rounded-[1.35rem] border border-slate-200 bg-white shadow-sm transition-all duration-200 hover:shadow-md"><button type="button" onClick={onToggle} className="flex w-full items-center justify-between gap-4 p-5 text-left" aria-expanded={isOpen}><h3 className="text-[14px] font-semibold text-slate-900 sm:text-[15px]">{faq.q}</h3><HiOutlineChevronDown className={`h-5 w-5 shrink-0 text-slate-400 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`} /></button><div className={`grid transition-all duration-300 ease-out ${isOpen ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'}`}><div className="overflow-hidden"><p className="px-5 pb-5 text-[13px] leading-[1.7] text-slate-500">{faq.a}</p></div></div></article>)
}

export default function CloudSolutionsPage() {
  const seo = getSeoForPath('/cloud-solutions')
  const [openFaq, setOpenFaq] = useState(0)
  return (<PublicPageShell backTo="/software-development" backLabel="Back to Software Dev" badge="Cloud Solutions" badgeIcon={HiOutlineCloud}><PageSeo {...seo} faqItems={faqs.map(f => ({ question: f.q, answer: f.a }))} /><nav aria-label="Breadcrumb" className="sr-only"><Link to="/">Home</Link><span> / </span><Link to="/software-development">Software Development</Link><span> / </span><span aria-current="page">Cloud Solutions</span></nav>
    <section className="relative overflow-hidden bg-[linear-gradient(180deg,#ffffff_0%,#f0f9ff_64%,#f1f5f9_100%)] pb-14 pt-20 sm:pb-18 sm:pt-24 lg:pb-20 lg:pt-28"><div className="soft-arc-bg pointer-events-none" /><div className="relative mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><p className="mt-7 inline-flex items-center gap-1.5 rounded-full border border-sky-200/60 bg-sky-50/70 px-4 py-2 text-xs font-medium uppercase tracking-[0.14em] text-sky-700 shadow-sm backdrop-blur-xl"><HiOutlineCloud className="h-3.5 w-3.5" />Cloud Solutions</p><h1 className="mt-5 max-w-4xl text-[2.5rem] font-semibold leading-[1.06] tracking-[-0.02em] text-slate-900 sm:text-[3.5rem] lg:text-[4.2rem]"><span className="bg-gradient-to-r from-sky-600 via-blue-600 to-cyan-600 bg-clip-text text-transparent">Cloud</span> Solutions</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-500 sm:text-lg">Cloud migration, DevOps, serverless architecture, and managed hosting. Deploy globally on Cloudflare, AWS, and Google Cloud with enterprise security.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full bg-slate-900 px-6 text-sm font-medium text-white shadow-[0_4px_16px_-6px_rgba(15,23,42,0.3)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-slate-800 active:scale-[0.97]">Discuss Cloud Setup <HiOutlineArrowRight className="text-lg" /></a><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full border border-slate-200/60 bg-white/80 px-6 text-sm font-medium text-slate-500 shadow-sm backdrop-blur-xl transition-all duration-200 hover:-translate-y-0.5 active:scale-[0.97]"><FaWhatsapp className="text-base text-emerald-500" />WhatsApp Us</a></div></div></section>
    <section data-reveal className="bg-white py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="text-center"><h2 className="text-3xl font-semibold tracking-[-0.02em] text-slate-900 sm:text-5xl">Cloud <span className="bg-gradient-to-r from-sky-600 via-blue-600 to-cyan-600 bg-clip-text text-transparent">Services</span></h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{services.map(s => (<article key={s.title} className="group flex flex-col rounded-[1.35rem] border border-slate-200/60 bg-white p-5 shadow-[0_4px_16px_-8px_rgba(15,23,42,0.05)] transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_14px_36px_-16px_rgba(15,23,42,0.16)]"><div className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-sky-100/80 text-sky-700 ring-1 ring-sky-200/60 transition-transform duration-300 group-hover:scale-110"><s.icon className="h-5 w-5" /></div><h3 className="mt-3 text-[14px] font-semibold text-slate-900">{s.title}</h3><p className="mt-2 flex-1 text-[12px] leading-[1.6] text-slate-500">{s.desc}</p></article>))}</div></div></section>
    <section data-reveal className="bg-white py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-3xl px-5 sm:px-6 lg:px-8"><div className="text-center"><h2 className="text-3xl font-semibold tracking-[-0.02em] text-slate-900 sm:text-5xl">Cloud <span className="bg-gradient-to-r from-sky-600 via-blue-600 to-cyan-600 bg-clip-text text-transparent">FAQs</span></h2></div><div className="mt-10 grid gap-3">{faqs.map((f, i) => <FaqItem key={f.q} faq={f} isOpen={openFaq === i} onToggle={() => setOpenFaq(openFaq === i ? -1 : i)} />)}</div></div></section>
    <section data-reveal className="px-5 pb-16 sm:px-6 sm:pb-20 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-6 rounded-[2rem] border border-sky-200/60 bg-[linear-gradient(135deg,#f0f9ff_0%,#ffffff_58%,#e0f2fe_100%)] p-6 shadow-md sm:p-8 lg:grid-cols-[1fr_auto]"><div><h2 className="text-3xl font-semibold tracking-tight text-slate-900 sm:text-4xl">Ready to Move to the Cloud?</h2><p className="mt-3 text-sm leading-7 text-slate-500">Free infrastructure assessment — we analyze your current setup and design your cloud architecture.</p></div><div className="flex flex-col gap-3 min-[420px]:flex-row"><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full bg-sky-600 px-6 text-sm font-medium text-white shadow-[0_4px_16px_-6px_rgba(14,165,233,0.3)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-sky-500 active:scale-[0.97]">Free Assessment <HiOutlineArrowRight className="text-lg" /></a><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full border border-slate-200/60 bg-white/80 px-6 text-sm font-medium text-slate-500 shadow-sm backdrop-blur-xl transition-all duration-200 hover:-translate-y-0.5 active:scale-[0.97]"><FaWhatsapp className="text-base text-emerald-500" />WhatsApp</a></div></div></section>
  </PublicPageShell>)
}
