import Link from '../../components/AppLink.jsx'
import { useState } from 'react'
import { HiOutlineArrowRight, HiOutlineArrowLeft, HiOutlineServerStack, HiOutlineCheckCircle, HiOutlineChartBar, HiOutlineUserGroup, HiOutlineCube, HiOutlineCalculator, HiOutlineCog8Tooth, HiOutlineShieldCheck, HiOutlineGlobeAlt, HiOutlineChevronDown } from 'react-icons/hi2'
import { FaWhatsapp } from 'react-icons/fa6'
import PageSeo from '../../components/PageSeo.jsx'
import { getSeoForPath } from '../../lib/seoMetadata.js'
import PublicPageShell from './PublicPageShell.jsx'
const WHATSAPP_URL = 'https://wa.me/923194329754'

const modules = [
  { icon: HiOutlineCalculator, title: 'Finance & Accounting', desc: 'General ledger, accounts payable/receivable, bank reconciliation, financial statements, budgeting, and multi-currency support.' },
  { icon: HiOutlineUserGroup, title: 'HR & Payroll', desc: 'Employee records, payroll processing, attendance, leave management, performance reviews, and compliance reporting.' },
  { icon: HiOutlineCube, title: 'Inventory & Warehouse', desc: 'Multi-warehouse stock tracking, batch/lot management, stock transfers, cycle counts, and real-time inventory valuation.' },
  { icon: HiOutlineServerStack, title: 'Procurement', desc: 'Purchase requisitions, vendor management, RFQ/RFP, purchase orders, goods receiving, and supplier performance tracking.' },
  { icon: HiOutlineChartBar, title: 'Business Intelligence', desc: 'Real-time dashboards, KPI tracking, drill-down reports, trend analysis, and AI-powered forecasting.' },
  { icon: HiOutlineCog8Tooth, title: 'Operations', desc: 'Production planning, quality control, maintenance management, work orders, and capacity planning.' },
  { icon: HiOutlineShieldCheck, title: 'Compliance', desc: 'Audit trails, regulatory reporting, tax compliance (GST/VAT), role-based access, and data retention policies.' },
  { icon: HiOutlineGlobeAlt, title: 'Multi-Branch', desc: 'Unified view across all locations. Inter-branch transfers, consolidated financials, and centralized master data.' },
]

const faqs = [
  { q: 'What is ERP and why does my business need it?', a: 'ERP (Enterprise Resource Planning) integrates all your core business processes — finance, HR, inventory, procurement — into one unified system. Instead of running separate software for each department, ERP gives you a single source of truth. Benefits: 30-50% less manual work, real-time visibility, better decisions, faster growth.' },
  { q: 'How much does a custom ERP cost?', a: 'Custom ERP starts at PKR 300,000 for a focused solution (2-3 modules) up to PKR 2,500,000+ for a full enterprise suite. We offer flexible payment terms and phased delivery — start with finance and add modules as you grow.' },
  { q: 'How long does ERP implementation take?', a: 'Focused ERP (2-3 modules): 8-12 weeks. Full enterprise ERP: 16-32 weeks. We use a phased approach — go live with core modules first, add more features over time. This reduces risk and lets your team adapt gradually.' },
  { q: 'Can you integrate with my existing accounting software?', a: 'Yes. We can build APIs to sync with QuickBooks, Xero, Tally, or any accounting system that provides an API. If no API exists, we build data import/export tools for seamless migration.' },
  { q: 'Is my data secure in a cloud ERP?', a: 'Enterprise-grade security: AES-256 encryption at rest, TLS 1.3 in transit, SOC 2 compliant infrastructure, daily automated backups, role-based access control, and full audit logging. Optional on-premise deployment for maximum data control.' },
  { q: 'Can multiple branches use the same ERP?', a: 'Yes — multi-branch is built into the core architecture. Each branch has its own data, inventory, and financials. Management gets a consolidated view with drill-down to individual branches.' },
]

function FaqItem({ faq, isOpen, onToggle }) {
  return (<article className="rounded-[1.35rem] border border-slate-200 bg-white shadow-[0_2px_12px_-4px_rgba(15,23,42,0.04)] transition-all duration-200 hover:shadow-[0_6px_20px_-8px_rgba(15,23,42,0.08)]"><button type="button" onClick={onToggle} className="flex w-full items-center justify-between gap-4 p-5 text-left" aria-expanded={isOpen}><h3 className="text-[14px] font-semibold text-slate-900 sm:text-[15px]">{faq.q}</h3><HiOutlineChevronDown className={`h-5 w-5 shrink-0 text-slate-400 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`} /></button><div className={`grid transition-all duration-300 ease-out ${isOpen ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'}`}><div className="overflow-hidden"><p className="px-5 pb-5 text-[13px] leading-[1.7] text-slate-500">{faq.a}</p></div></div></article>)
}

export default function ERPDevelopmentPage() {
  const seo = getSeoForPath('/erp-development')
  const [openFaq, setOpenFaq] = useState(0)
  return (<PublicPageShell backTo="/software-development" backLabel="Back to Software Dev" badge="ERP Solutions" badgeIcon={HiOutlineServerStack}><PageSeo {...seo} faqItems={faqs.map(f => ({ question: f.q, answer: f.a }))} /><nav aria-label="Breadcrumb" className="sr-only"><Link to="/">Home</Link><span> / </span><Link to="/software-development">Software Development</Link><span> / </span><span aria-current="page">ERP Solutions</span></nav>
    <section className="relative overflow-hidden bg-[linear-gradient(180deg,#ffffff_0%,#f5f3ff_64%,#f1f5f9_100%)] pb-14 pt-20 sm:pb-18 sm:pt-24 lg:pb-20 lg:pt-28"><div className="soft-arc-bg pointer-events-none" /><div className="relative mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><p className="mt-7 inline-flex items-center gap-1.5 rounded-full border border-violet-200/60 bg-violet-50/70 px-4 py-2 text-xs font-medium uppercase tracking-[0.14em] text-violet-700 shadow-sm backdrop-blur-xl"><HiOutlineServerStack className="h-3.5 w-3.5" />ERP Solutions</p><h1 className="mt-5 max-w-4xl text-[2.5rem] font-semibold leading-[1.06] tracking-[-0.02em] text-slate-900 sm:text-[3.5rem] lg:text-[4.2rem]"><span className="bg-gradient-to-r from-violet-600 via-purple-600 to-fuchsia-600 bg-clip-text text-transparent">ERP</span> Solutions</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-500 sm:text-lg">Unify finance, HR, inventory, procurement, and operations into one platform. Real-time dashboards, complete visibility, better decisions.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full bg-slate-900 px-6 text-sm font-medium text-white shadow-[0_4px_16px_-6px_rgba(15,23,42,0.3)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-slate-800 active:scale-[0.97]">Discuss Your ERP <HiOutlineArrowRight className="text-lg" /></a><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full border border-slate-200/60 bg-white/80 px-6 text-sm font-medium text-slate-500 shadow-sm backdrop-blur-xl transition-all duration-200 hover:-translate-y-0.5 active:scale-[0.97]"><FaWhatsapp className="text-base text-emerald-500" />WhatsApp Us</a></div></div></section>
    <section data-reveal className="bg-white py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="text-center"><h2 className="text-3xl font-semibold tracking-[-0.02em] text-slate-900 sm:text-5xl">ERP <span className="bg-gradient-to-r from-violet-600 via-purple-600 to-fuchsia-600 bg-clip-text text-transparent">Modules</span></h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{modules.map(m => (<article key={m.title} className="group flex flex-col rounded-[1.35rem] border border-slate-200/60 bg-white p-5 shadow-[0_4px_16px_-8px_rgba(15,23,42,0.05)] transition-all duration-300 hover:-translate-y-1 hover:shadow-[0_14px_36px_-16px_rgba(15,23,42,0.16)]"><div className="inline-flex h-10 w-10 items-center justify-center rounded-xl bg-violet-100/80 text-violet-700 ring-1 ring-violet-200/60 transition-transform duration-300 group-hover:scale-110"><m.icon className="h-5 w-5" /></div><h3 className="mt-3 text-[14px] font-semibold text-slate-900">{m.title}</h3><p className="mt-2 flex-1 text-[12px] leading-[1.6] text-slate-500">{m.desc}</p></article>))}</div></div></section>
    <section data-reveal className="bg-white py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-3xl px-5 sm:px-6 lg:px-8"><div className="text-center"><h2 className="text-3xl font-semibold tracking-[-0.02em] text-slate-900 sm:text-5xl">ERP <span className="bg-gradient-to-r from-violet-600 via-purple-600 to-fuchsia-600 bg-clip-text text-transparent">FAQs</span></h2></div><div className="mt-10 grid gap-3">{faqs.map((f, i) => <FaqItem key={f.q} faq={f} isOpen={openFaq === i} onToggle={() => setOpenFaq(openFaq === i ? -1 : i)} />)}</div></div></section>
    <section data-reveal className="px-5 pb-16 sm:px-6 sm:pb-20 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-6 rounded-[2rem] border border-violet-200/60 bg-[linear-gradient(135deg,#f5f3ff_0%,#ffffff_58%,#ede9fe_100%)] p-6 shadow-md sm:p-8 lg:grid-cols-[1fr_auto]"><div><h2 className="text-3xl font-semibold tracking-tight text-slate-900 sm:text-4xl">Ready to Unify Your Business Operations?</h2><p className="mt-3 text-sm leading-7 text-slate-500">Free consultation — we analyze your workflows and design your ideal ERP.</p></div><div className="flex flex-col gap-3 min-[420px]:flex-row"><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full bg-violet-600 px-6 text-sm font-medium text-white shadow-[0_4px_16px_-6px_rgba(139,92,246,0.3)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-violet-500 active:scale-[0.97]">Get Free Consultation <HiOutlineArrowRight className="text-lg" /></a><a href={WHATSAPP_URL} target="_blank" rel="noreferrer" className="inline-flex min-h-[44px] items-center gap-2 rounded-full border border-slate-200/60 bg-white/80 px-6 text-sm font-medium text-slate-500 shadow-sm backdrop-blur-xl transition-all duration-200 hover:-translate-y-0.5 active:scale-[0.97]"><FaWhatsapp className="text-base text-emerald-500" />WhatsApp</a></div></div></section>
  </PublicPageShell>)
}
